-- 0024_extensiones_renta.sql
-- Tabla de historial de extensiones de rentas (horas o días extras agregados)

CREATE TABLE extensiones_renta (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_renta INTEGER NOT NULL,
    tipo VARCHAR(10) NOT NULL,           -- 'horas' o 'dias'
    cantidad INTEGER NOT NULL,           -- cantidad de horas o días
    valor_unitario DECIMAL(12,2) NOT NULL, -- valor por hora/día
    valor_total DECIMAL(12,2) NOT NULL,  -- cantidad × valor_unitario
    observaciones VARCHAR(500),
    usuario VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_extension_renta FOREIGN KEY (id_renta) REFERENCES rentas(id)
);

-- Índice para buscar extensiones por renta
CREATE INDEX idx_extensiones_renta_id ON extensiones_renta(id_renta);
